spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/swiss-dg-db}
    username: ${JDBC_DATABASE_USERNAME:${DB_USERNAME_DEV}}
    password: ${JDBC_DATABASE_PASSWORD:${DB_PASSWORD_DEV}}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
error:
  handling:
    full-stacktrace-http-statuses: 5xx
server:
  error:
    include-message: always
  address: 0.0.0.0
  port: 8080
app:
  frontend:
    url: "http://localhost:4200"
    urlDiscgolf: "http://172.20.10.2:4200"
logging:
  level:
    root: INFO
    dg.swiss.swiss_dg_db: DEBUG




